### ISSUE TITLE
Cloning complex model relationships

### ISSUE THREAD

**Issue by fabianallendorf** [tj-django/django-clone#175]
**Is your feature request related to a problem? Please describe.**
I have a complex database structure. Its better to be explained using an example:

```python
class House(CloneMixin, models.Model):
   _clone_many_to_one_or_one_to_many_fields = ["rooms", "furniture"]  # either this

class Room(CloneMixin, models.Model):
   _clone_many_to_one_or_one_to_many_fields = ["furniture"]  # or this?

  house = models.ForeignKey(House, related_name="rooms")

class Furniture(CloneMixin, models.Model):
  house = models.ForeignKey(House, related_name="furniture")
  room = models.ForeignKey(Room, related_name="furniture")
```
Lets say I want to clone a `House` object which has a few `Room` and `Furniture` objects. The problem arises that, when it clones a `Furniture` object, it will update the foreign key to `house` but not `room`. Or when I clone `Room` it will update the `room` foreign key but not the `house` foreign key. 

This way I can imagine to end up in a state where cloned Furniture objects exist twice with either a reference to `Room` or `House` missing.

**Describe the solution you'd like**
I would want to have a mechanism were I can tell the `Furniture` during cloning that it has to update both foreign keys accordingly.

**Describe alternatives you've considered**
Passing a map of old and new instances down the foreign key relationship path which lower level objects can access to update every foreign key.

**Comment by jackton1** [comment]
@fabianallendorf This might be resolved now but I'll setup a test to replicate.

**Comment by jackton1** [comment]
@fabianallendorf Let me know if this is still a blocker ?

**Comment by jackton1** [comment]
@fabianallendorf closing this issue for now let me know if this is still an issue using the latest version.
