### ISSUE TITLE
Implicit declaration of ManyToManyField, auto_created is of type "CloneMetaClass"

### ISSUE THREAD

**Issue by zivkovic** [tj-django/django-clone#184]
Using django-clone version 0.2.0
Using django version 2.2.7

This has to be a bug since per [django documentation](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.Field.auto_created) this field is of type boolean and can only hold True or False values. But in the case where you do not specify a through model for a ManyToMany field, it somehow gets set to a value of class "CloneMetaClass".

To reproduce, do the following:
```
class TestA(models.Model):
    name = models.TextField(_('Name'), max_length=512, blank=True)

class TestB(CloneMixin, models.Model):
    tests_a= models.ManyToManyField('app.TestA', related_name='tests_a', blank=True)

    _clone_many_to_many_fields = [
        'tests_a'
    ]
```

and then use:
`test_b_instance.make_clone()`

When make_clone is called, the following code fails(clone.py, line 346):
``` 
# Clone many to many fields
for field in many_to_many_fields:
    if all(
        [
            field.remote_field.through,
            not field.remote_field.through._meta.auto_created,
        ]
    ):
```
because "not field.remote_field.through._meta.auto_created" is not a boolean but of type "CloneMetaClass".

If I specifically use through class, then it works as it should. But I do not see the logic why you would want it to fail if you don't specify the through class and instead use the implicitly generated class by django.

Screenshot from PyCharm where it is seen that auto_created is of type "CloneMetaClass":
![image](https://user-images.githubusercontent.com/2651524/92324788-1c835480-f045-11ea-8969-4932f58e94de.png)

If by some chance this is "correct", then please set the auto_created to True instead of assigning it a type of "CloneMetaClass".

Looking forward to your reply.

Best regards, Jan

**Comment by jackton1** [comment]
@zivkovic This should be resolved in the latest release https://pypi.org/project/django-clone/1.1.1/
