### ISSUE TITLE
[BUG] when cloning, images are not created but are linked to the source image

### ISSUE THREAD

**Issue by ssokwebcase** [tj-django/django-clone#268]
**Describe the bug**
When cloning, images are not created but are linked to the source, if delete/change image in source - then lost image in recipient and vice versa

**To Reproduce**
1. Create original **object_1** where must be field **image**
2. Clone **object_1** -> created **object_1-copy-1**
3. path **image** in **object_1** and **object_1-copy-1** - **same**
4. Drop/change image in **object_1**(or object_1-copy-1) -> delete original image from disk, and image not available from another object - **object_1-copy-1**(or object_1)
5. if try change where fail image **object_1-copy-1**(or object_1) - get error file not exists

**Expected behavior**
When cloned object expected what image was create new file, not linked to source

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Django 3.0
 - django-clone 2.3.3

May be this problem with and FileField

**Comment by ssokwebcase** [comment]
I was wrong

**Comment by AbdulmalikGiwa** [comment]
> I was wrong

I don't think you are, because I'm facing the same issue. Or better still how did you go about it?

**Comment by ssokwebcase** [comment]
I use packege that removes image from os if we remove from admin(saving space and fast work). By default django no drop file from OS. But you right django-clone copy path - no file, as result we have two field - one path - maybe its not good. I overide CloneMixin and after super copy image file. Example
import os

from model_clone import CloneMixin
from django.db import transaction
from django.core.files.base import ContentFile


class CloneWithImageMixin(CloneMixin):
    @transaction.atomic
    def make_clone(self, attrs=None, sub_clone=False):
        duplicate = super().make_clone(attrs=None, sub_clone=False)
        duplicate.image.save(
            os.path.basename(self.image.name),
            ContentFile(self.image.read())
        )

        return duplicate
image - field in my model
