### ISSUE TITLE
`UniqueConstraint` in Model Meta is not considered

### ISSUE THREAD

**Issue by diesieben07** [tj-django/django-clone#330]
**Describe the bug**
If a field is made unique via a `UniqueConstraint` it is not detected as unique and thus cloning the model will result in constraint errors instead of `copy` being appended to the field.

**To Reproduce**
1. Create a `UniqueConstraint` for a `CharField` via Model `Meta`.
2. Try to clone the model.
3. Observe `IntegrityError` being thrown.

**Expected behavior**
`UniqueConstraint`s should be detected.

**Desktop (please complete the following information):**
 - Version 2.5.3

**Additional context**
I don't think the fix for this is simply treating the fields as unique and appending "copy" to them. While that will probably remove the constraint error, it might not be what is desired, as a `UniqueConstraint` might have multiple fields (the same applies to `unique_together`) or even a condition.
It would be useful to provide a hook for models / fields to provide their own "get new unique value"-logic. This would additionally enable fields other than `CharField` to work with unique.

**Comment by jackton1** [comment]
@diesieben07 This can now be done via the field.default kwargs

```py

def get_unique_value():
    return 

class MyModel(models.Model):
	my_unique_field = models.CharField(max_length=255, default=get_unique_value)

	class Meta:
		constraints = [
			UniqueConstraint(...),
        ]

```
