### ISSUE TITLE
[BUG] - Duplicated models are not always created in same database

### ISSUE THREAD

**Issue by NodeJSmith** [tj-django/django-clone#366]
**Describe the bug**
Duplicated models do not retain the same database as the original, if the original database is not the default.

**To Reproduce**
With settings that include a router that determines database from request (ie, models are not linked to specific database), call make_clone on an instance that is from a non-default database. The clone will be created in the default database, not the same database as the original instance.

**Expected behavior**
The clone should be created in the same database as the original instance.

**Screenshots**
![2021-06-18 10_35_52-Remote Desktop Manager Free  cls-md-dbwebdv1](https://user-images.githubusercontent.com/8505845/122586485-5cd72080-d022-11eb-8a1e-08d28b1b39d1.png)
![2021-06-18 10_38_00-Remote Desktop Manager Free  cls-md-dbwebdv1](https://user-images.githubusercontent.com/8505845/122586444-4f219b00-d022-11eb-84c4-df3c1343e33b.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Version v2.5.3

**Additional context**
I got it working (basic testing) correctly by changing make_clone duplicate.save to:

```
db = self._state.db
duplicate.save(using=db)
```

and for create_copy_of_instance:

```
db = instance._state.db
new_obj = instance.__class__.objects.using(db).create(**defaults)
```

**Comment by jackton1** [comment]
Thanks @NodeJSmith the latest [v2.6.x](https://pypi.org/project/django-clone/2.6.1/) version should include the bug fix.

Also Thanks for coffee.
