### ISSUE TITLE
UUIDField with unique re-uses previous value and raises an IntegrityError

### ISSUE THREAD

**Issue by inerte** [tj-django/django-clone#381]
**Describe the bug**

Per Django's documentation snippet around UUIDField https://docs.djangoproject.com/en/3.2/ref/models/fields/#uuidfield it's acceptable to use `primary_key=True, default=uuid.uuid4, editable=False`. In my particular case, the UUID isn't the model primary key, but it has `unique=True`.

When duplicating a model with such configuration, an IntegrityError is raised.

**To Reproduce**
1. Create a model with `uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)`
2. Try to duplicate it using django-clone
3. **IntegrityError** is raised, `duplicate key value violates unique constraint`...

**Expected behavior**
The field is unique, but has a `default` callable. It should use the value generated by the callable.

**Additional context**

This might be a more specific instance of #330 - I've created a new issue because I believe this field can be treated differently like it's done with `models.DateTimeField, models.DateField` here: https://github.com/tj-django/django-clone/blob/52e35707efe193ee15542a7019059285e3a3c495/model_clone/mixins/clone.py#L326

A few lines above when `value = getattr(instance, f.attname, f.get_default())` is called, `f.get_default()` actually invokes `uuid.uuid4` and a new UUID is generated, but `getattr` finds `f.attname` already there (the `uuid`), so it re-uses.

I propose another special case for `UUIDField`, just because Django's documentation explicitly contains a hint that might lead django-clone to fail. Something simple as

```python
if isinstance(f, UUIDField):
    value = f.get_default()
```

Should suffice, but the conditional can be fancier.

Another approach would be to always identify if the default is callable, and call it, no matter the field type. While less specific, it probably does what the user intended more often, which is to execute the callable when saving the field for the first time.

Either way, I can create a PR if needed. Thoughts on either approach or perhaps another direction I should take?

**Comment by jackton1** [comment]
@inerte Your correct this is a valid use case and a bug that is a result of using the source instance value and falling back to the default specified on the field.

This should be resolved in the latest release. 

Thanks
