### ISSUE TITLE
[BUG] Cloning fails with nullable strings on regex

### ISSUE THREAD

**Issue by dustinchilson** [tj-django/django-clone#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

A model field of `models.CharField(max_length=255, null=True)` with a null or None value causes the clone to fail. 

`TypeError: expected string or bytes-like object`

### To Reproduce

1. Create a model that implements the `CloneMixin`
2. Include a nullable char column
3. `obj = Model.objects.create()`, explicitly not setting the nullable column
4. `obj2 = obj.make_clone()`

### What OS are you seeing the problem on?

linux

### Expected behavior?

The object would clone as expected.

### Relevant log output

```shell
/usr/local/lib/python3.9/contextlib.py:79: in inner
    return func(*args, **kwds)
.venv/lib/python3.9/site-packages/model_clone/mixins/clone.py:234: in make_clone
    duplicate = self._create_copy_of_instance(self, using=using)
.venv/lib/python3.9/site-packages/model_clone/mixins/clone.py:372: in _create_copy_of_instance
    value = clean_value(value, unique_duplicate_suffix)
.venv/lib/python3.9/site-packages/model_clone/utils.py:151: in clean_value
    return re.sub(r"([\s-]?){}[\s-][\d]$".format(suffix), "", value, flags=re.I)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pattern = '([\\s-]?)copy[\\s-][\\d]$', repl = '', string = None, count = 0
flags = re.IGNORECASE

    def sub(pattern, repl, string, count=0, flags=0):
        """Return the string obtained by replacing the leftmost
        non-overlapping occurrences of the pattern in string by the
        replacement repl.  repl can be either a string or a callable;
        if a string, backslash escapes in it are processed.  If it is
        a callable, it's passed the Match object and must return
        a replacement string to be used."""
>       return _compile(pattern, flags).sub(repl, string, count)
E       TypeError: expected string or bytes-like object
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dustinchilson** [comment]
Missed a variable, it also has a uniqueness constraint on the nullable column, other nullable char fields seem to work fine, but this one is required to be set.

```
class Meta:
        constraints = [
            models.UniqueConstraint(
                name="uq_nullable_col", fields=["nullable_col"]
            ),
        ]
```

**Comment by jackton1** [comment]
Just curious was there a reason why a string field would be nullable ??

https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.Field.null

```
Avoid using null on string-based fields such as CharField and TextField. If a string-based field has null=True, that means it has two possible values for “no data”: NULL, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” the Django convention is to use the empty string, not NULL. One exception is when a CharField has both unique=True and blank=True set. In this situation, null=True is required to avoid unique constraint violations when saving multiple objects with blank values.

For both string-based and non-string-based fields, you will also need to set blank=True if you wish to permit empty values in forms, as the null parameter only affects database storage (see blank).
```

**Comment by dustinchilson** [comment]
I am using Django Rest Framework, and in most cases my field is not null, but when it is the null in PostgreSQL is not considered equal in a unique constraint, 

https://www.postgresql.org/docs/current/indexes-unique.html

I set `null=true` and manually add a UniqueConstraint of two columns including the nullable `CharField`, effectively setting `unique=True` (can't do `unique=True` as I need the second column as part of the constraint)

All of this said, just because I can do it, doesn't mean I should and there may be benefit of reconsidering the `null=true`.

**Comment by jackton1** [comment]
@dustinchilson This should be resolved in the latest release. Thanks

**Comment by dustinchilson** [comment]
Thanks, I'll give it a try. I appreciate the help.
