### ISSUE TITLE
[Feature] Option to modify cloned object before saving

### ISSUE THREAD

**Issue by theomega** [tj-django/django-clone#469]
### Is your feature request related to a problem? Please describe.

I'm searching for the possibility to modify some of the fields before on the cloned object. Two examples:
- I have a field `added_by` which keeps track which Django User added the object. When cloning, I want this to be set to the current user and not the user of the original object.
- I want to make clear in some string-field, that this object is a clone by adding `(Cloned)` or similar. The string field is a unique field.

### Describe the solution you'd like?

A method in the model which gets called after the whole cloned object has been constructed but before it is saved would help here. The method could be empty per default and be overwritten in case the user needs it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theomega** [comment]
Thank you @jackton1 for the quick addition, I really appreciate your time and your effort for this open source project!

**Comment by jackton1** [comment]
Your welcome @theomega
