### ISSUE TITLE
[BUG] 2.9.5 now clones the o2o which clones the original again, so too many clones

### ISSUE THREAD

**Issue by tuky** [tj-django/django-clone#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

https://github.com/tj-django/django-clone/commit/5a2e65dde0f21b47ec4adc43be5acb6d9f868cde introduces a bug where the easiest o2o configuration will create too many clones. My guess is that this PR https://github.com/tj-django/django-clone/pull/493 introduces one more level of recursion that is too much.

### To Reproduce

To reproduce, I created this toy model setup:

```python
class Sentence(CloneMixin, models.Model):
    _clone_o2o_fields = {'ending'}


class Ending(CloneMixin, models.Model):
    sentence = models.OneToOneField(Sentence, on_delete=models.CASCADE, related_name='ending')
```

with this setup I have a test that worked in 2.9.4 but is now failing:

```python
class CloneTest(TestCase):
    def test_clone(self):
        sentence = Sentence.objects.create()
        Ending.objects.create(sentence=sentence)

        self.assertEqual(1, Sentence.objects.count())
        self.assertEqual(1, Ending.objects.count())

        clones = [sentence.make_clone() for _ in range(2)]

        self.assertEqual(2, len(clones))
        self.assertEqual(3, Sentence.objects.count())  # breaks with AssertionError: 3 != 5
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The test should work and there should be only 3 Sentences (2 clones and 1 original).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@tuky This should be resolved in the latest release

**Comment by tuky** [comment]
thank you so much. wondering what a good solution for https://github.com/tj-django/django-clone/issues/488 would be then, but we weren't affected by that :sweat_smile:
