### ISSUE TITLE
[BUG] m2m fields are cloned even if _clone_m2m_fields is empty

### ISSUE THREAD

**Issue by benedikt-bartscher** [tj-django/django-clone#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When setting `_clone_m2m_fields = []` for a clone model m2m fields are cloned anyway.

### To Reproduce

Create a Model with CloneMixin and set
`_clone_m2m_fields = []`

### Expected behavior?

m2m fields are not cloned

### Anything else?

It would be nice to set different behaviours for m2m fields like:
- SET_NULL (just clears m2m fields)
- CLONE (clone referenced objects, current behaviour)
- LINK (create m2m relations with existing objects new.m2mfield.set(old.m2mfield.all())

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@benedikt-bartscher To clarify see the test in the linked PR as the default `_clone_m2m_fields = []`
