### ISSUE TITLE
__duplicate_m2m_fields doesn't work for other db with 'through' attribute

### ISSUE THREAD

**Issue by accedx** [tj-django/django-clone#815]
Hello, if model field has 'through' attribute, that code doesn't use source model instance db id

https://github.com/tj-django/django-clone/blob/a401427bddc3d4be267400ce030ea08b66f92f4d/model_clone/mixin.py#L664C24-L664C24

I suggest add 'using' to 'through.objects'
`objs = through.objects.using(self._state.db).filter(**{field_name: self.pk})`

Or remove this 'if', and leave only code into 'else' branch. 'Else' branch work perfectly for 'through' if is exists.

`

        for field in fields:
            if hasattr(field, "field"):
                # ManyToManyRel
                field_name = field.field.m2m_reverse_field_name()
                through = field.through
                source = getattr(self, field.get_accessor_name())
                destination = getattr(duplicate, field.get_accessor_name())
            else:
                through = field.remote_field.through
                field_name = field.m2m_field_name()
                source = getattr(self, field.attname)
                destination = getattr(duplicate, field.attname)

            items_clone = []
            for item in source.all():
                if hasattr(item, "make_clone"):
                    try:
                        item_clone = item.make_clone(
                            using=using,
                        )
                    except IntegrityError:
                        item_clone = item.make_clone(
                            sub_clone=True,
                            using=using,
                        )
                else:
                    item_clone = CloneMixin._create_copy_of_instance(
                        item,
                        force=True,
                        sub_clone=True,
                        using=using,
                    )
                    item_clone.save(using=using)
                    items_clone.append(item_clone)

                destination.set(items_clone)

        return duplicate
`

**Comment by jackton1** [comment]
This issue doesn’t follow the issue template and as such wouldn’t be considered. Please create an issue with the issue template and describe the issue you are facing in more detail.
